name: LuaRocks release
on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  luarocks-release:
    runs-on: ubuntu-24.04
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        with:
          dependencies: |
            lua-cjson
          test_dependencies: |
            busted
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
